name: markaseddon
favicon: null
layout_spectrum: 0.09435357502661645
typography_spectrum: 0.54961
title: Musings on Technology
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222224'
    - '#ffffff'
    - '#02d5e8'
    - '#7c5744'
    - '#f34f4f'
  brandStrength: 0.1688509932719171
  lightness: 0.8125
  saturation: 0.7458458938635886
  rhythmicContrast: 0.6922202124260366
purpose: []
